blank_issues_enabled: false
contact_links:
  - name: Documentación del proyecto
    url: https://github.com/track-hub-team/track-hub-2/tree/main/docs
    about: Consulta la documentación antes de crear una issue
